### ISSUE TITLE
How do I even open this program?

### ISSUE THREAD

**Issue by rhigosrebel** [Sejemus/Tower-Unite-Piano-Bot#4]
I can see no .EXE or any guide on opening this? Help?

**Comment by OfficialHisha** [comment]
Hello, sorry for the late reply, for some reason github doesn't always inform me of tickets :/
This is the sourcecode for the program, so in order to use it you have to compile it.
If you do not wish to, or do not know how to, compile the code you can download the program from my thread here: http://forums.pixeltailgames.com/t/piano-player/10070/91?u=matias
